name: RStein.TOML build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dotnet_version: '9.0.x'
            dotnet_quality: 'ga'
            framework: 'net9.0'
          - dotnet_version: '10.0.x'
            dotnet_quality: 'ga'
            framework: 'net10.0'
          - dotnet_version: '11.0.x'
            dotnet_quality: 'preview'
            framework: 'net11.0'
    steps:
    - uses: actions/checkout@v4
    - name: Remove pre-installed dotnet
      run: sudo rm -rf /usr/share/dotnet
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet_version }}
        dotnet-quality: ${{ matrix.dotnet_quality }}
    - name: Restore dependencies
      run: dotnet restore -p:TargetFrameworks=${{ matrix.framework }}
    - name: Build
      run: dotnet build --no-restore -f ${{ matrix.framework }}
    - name: Test
      run: dotnet test --no-build --verbosity normal -f ${{ matrix.framework }}

  build_win:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9 (Windows)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Setup .NET 10 (Windows)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    - name: Setup .NET 11 (Windows)
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '11.0.x'
        dotnet-quality: 'preview'

    - name: build + test
      run: build.bat
      shell: cmd
      working-directory: ${{ github.workspace }}
  deploy-docs:
    runs-on: ubuntu-latest
    needs: [build_ubuntu]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Remove pre-installed dotnet
        run: sudo rm -rf /usr/share/dotnet

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Setup .NET 11
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '11.0.x'
          dotnet-quality: 'preview'

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Build Docs
        run: docfx doc/docfx.json

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: doc/_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
