name: RStein.TOML build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build_ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:      
        dotnet_version: ['9.0.x', '10.0.x']
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet_version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build_win:
    name: Windows
    runs-on: windows-latest   
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9 (Windows)
      uses: actions/setup-dotnet@v4
      with:  
        dotnet-version: '9.0.x'
    - name: Setup .NET 10 (Windows)
      uses: actions/setup-dotnet@v4
      with:  
        dotnet-version: '10.0.x'
    - name: build + test
      run: build.bat
      shell: cmd
      working-directory: ${{ github.workspace }}
  deploy-docs:
    runs-on: ubuntu-latest   
    needs: [build_ubuntu] 
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Build Docs      
        run: docfx doc/docfx.json

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:        
          path: doc/_site 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
